main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path("", views.Home.as_view(), name="home"),
  path("about/", views.about, name="about"),
  path("musicians/", views.musicians_index, name="musicians_index"),
  path("musicians/<int:musician_id>/", views.musicians_detail, name="musicians_detail"),
  path("musicians/create/", views.MusicianCreate.as_view(), name="musicians_create"),
  path("musicians/<int:pk>/update/", views.MusicianUpdate.as_view(), name="musicians_update"),
  path("musicians/<int:pk>/delete/", views.MusicianDelete.as_view(), name="musicians_delete"),
  path("musicians/<int:musician_id>/add_song/", views.add_song, name="add_song"),
  path("streams/create/", views.StreamingCreate.as_view(), name="streams_create"),
  path("streams/<int:pk>/", views.StreamingDetail.as_view(), name="streams_detail"),
  path("streams/", views.StreamingList.as_view(), name="streams_index"),
  path("streams/<int:pk>/update/", views.StreamingUpdate.as_view(), name="streams_update"),
  path("streams/<int:pk>/delete/", views.StreamingDelete.as_view(), name="streams_delete"),
  path("musicians/<int:musician_id>/assoc_streaming/<int:streaming_id>/", views.assoc_streaming, name="assoc_streaming"),
  path("accounts/signup/", views.signup, name="signup")
]

musiciancollector/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("main_app.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls"))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Streaming(models.Model):
  streaming_service = models.CharField(max_length=50)

  def __str__(self):
    return self.streaming_service

  def get_absolute_url(self):
    return reverse("streams_detail", kwargs={"pk": self.id})

class Musician(models.Model):
  name = models.CharField(max_length=100)
  genre = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  age = models.IntegerField()
  streams = models.ManyToManyField(Streaming)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse("musicians_detail", kwargs={"musician_id": self.id})

class Song(models.Model):
  song_name = models.CharField(max_length=50)
  album = models.CharField(max_length=50)

  musician = models.ForeignKey(Musician, on_delete=models.CASCADE)

  def __str__(self):
    return self.song_name

main_app/forms.py
from django.forms import ModelForm, fields
from .models import Song

class SongForm(ModelForm):
  class Meta:
    model = Song
    fields = ["song_name", "album"]

main_app/views.py
from django import contrib
from django.contrib.auth.forms import UserCreationForm
from django.db.models import fields
from django.http import request
from django.shortcuts import redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Musician, Streaming
from .forms import SongForm
from main_app import models

# Create your views here.

class Home(LoginView):
  template_name = "home.html"

def about(request):
  return render(request, "about.html")

@login_required
def musicians_index(request):
  musicians = Musician.objects.filter(user=request.user)
  return render(request, "musicians/index.html", { "musicians" : musicians})

@login_required
def musicians_detail(request, musician_id):
  musician = Musician.objects.get(id=musician_id)
  streams_musician_doesnt_have = Streaming.objects.exclude(id__in = musician.streams.all().values_list("id"))
  song_form = SongForm()
  return render(request, "musicians/detail.html", { "musician" : musician, "song_form" : song_form, "streams" : streams_musician_doesnt_have})

class MusicianCreate(LoginRequiredMixin ,CreateView):
  model = Musician
  fields = ["name", "genre", "description", "age"]

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class MusicianUpdate(LoginRequiredMixin ,UpdateView):
  model = Musician
  fields = ["genre", "description", "age"]

class MusicianDelete(LoginRequiredMixin ,DeleteView):
  model = Musician
  success_url = "/musicians/"

@login_required
def add_song(request, musician_id):
  form =  SongForm(request.POST)
  if form.is_valid():
    new_song = form.save(commit=False)
    new_song.musician_id = musician_id
    new_song.save()
  return redirect("musicians_detail", musician_id=musician_id)

class StreamingCreate(LoginRequiredMixin ,CreateView):
  model = Streaming
  fields = "__all__"

class StreamingList(LoginRequiredMixin ,ListView):
  model = Streaming

class StreamingDetail(LoginRequiredMixin ,DetailView):
  model = Streaming

class StreamingUpdate(LoginRequiredMixin ,UpdateView):
  model = Streaming
  fields = "__all__"

class StreamingDelete(LoginRequiredMixin ,DeleteView):
  model = Streaming
  success_url = "/streams/"

@login_required
def assoc_streaming(request, musician_id, streaming_id):
  Musician.objects.get(id=musician_id).streams.add(streaming_id)
  return redirect("musicians_detail", musician_id=musician_id)

def signup(request):
  error_message = ""
  if request.method == "POST":
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect("musicians_index")
    else:
      error_message = "Invalid sign up, please try again"
  form = UserCreationForm()
  context = {"form": form, "error_message": error_message}
  return render(request, "signup.html", context)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}

<h1>About the Musician Collector</h1>
<hr />
<p>
  I am in love with everything music, I make it my goal to know everything music!!
</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href=""
  >
  <title>Musician Collector</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-logo-container">
      <a href="{% url 'home' %}">
        <img 
          class="head-logo"
          src="{% static 'images/header-logo.png' %}" 
          style="width:3em; height:3em;"
          alt="The Musician Collector Logo"
        >
      </a>
    </div>
    <nav>
      <ul>
      {% if user.is_authenticated %}
        <li><a href="{% url 'musicians_index' %}">All Musicians</a></li>
        <li><a href="{% url 'streams_index' %}">All Streaming Services</a></li>
        <li><a href="{% url "musicians_create" %}">Add Musician</a></li>
        <li><a href="{% url "streams_create"%}">Add Streaming Service</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url "logout" %}">Logout</a></li>
      {% else %}
        <li><a href="{% url 'about' %}">About</a></li>
        <li><a href="{% url "home"%}">Login</a></li>
        <li><a href="{% url "signup" %}">Signup</a></li>
      {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <div class="image-container">
    <img 
    src="{% static 'images/home-image.png' %}" 
    alt="The Musician Collector"
    style="width: 50em" "height: 50em" />
  </div>
</section>
{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}
{% endblock %}

main_app/templates/main_app/musician_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Musician?</h1>
  <img src="{% static 'images/' %}" alt=""/>
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'musicians_detail' musician.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/musician_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  {% if object %}
  <h1>Edit {{ object.name }}</h1>
  {% else %}
  <h1>Add a Musician</h1>
  {% endif %}
  <img src="{% static '' %}" alt=""/>
</div>
<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/streaming_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="page-header">
  <h1>Delete Streaming Service?</h1>
</div>
<h2>Are you sure you want to delete {{ object.streaming_service }}?</h2>

<form action="" method="POST" class="form">
  {% csrf_token %}
  <a 
    href="{% url 'streams_detail' streaming.id %}" 
    class="btn secondary"
  >
    Cancel
  </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/streaming_detail.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/streaming-detail.css' %}"
/>
{% endblock %}

{% block content %}

<div class="card-content">
  <h2>{{ streaming.streaming_service }}</h2>
</div>
<a href="{% url 'streams_update' streaming.id %}" class="btn warn">Edit</a>
<a href="{% url 'streams_delete' streaming.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/main_app/streaming_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}
<div class="page-header">
  {% if object %}
    <h1>Edit {{object.name}}</h1>
  {% else %}
    <h1>Add a Streaming Service</h1>
  {% endif %}
  <img src="{% static '' %}" alt=""/>
</div>
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/streaming_list.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/streaming-index.css' %}"
/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>All Musicians Streaming Services</h1>
</section>

<section class="card-container">
  {% for streaming in streaming_list %}
  <div class="card" style="border-color=black">
    <div class="card-bg" style="background-color: rgba(218, 123, 34, 0.9)"></div>
    <a href="{% url 'streams_detail' streaming.id %}">
      <div class="card-content">
        <h2>{{ streaming.streaming_service }}</h2>
      </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/musicians/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/musician-detail.css' %}"
/>
{% endblock %}

{% block content %}

<section class="musician-container">
  <div class="musician-img">
    <img 
      src="{% static 'images/musician-icon.svg' %}" 
      alt="A Musician"
    >
  </div>
  <div class="musician-details">
    <h1>{{ musician.name }}</h1>
      <h2>Is a {{ musician.age }} year old {{ musician.genre }} artist.</h2>
      <p><small>{{ musician.description }}</small></p>
    <div class="musician-actions">
      <a href="{% url "musicians_update" musician.id %}" class="btn warn">Update</a>
      <a href="{% url "musicians_delete" musician.id %}" class="btn danger">Delete</a>
    </div>
  </div>
</section>
<div class="songs-toy-container">
  <section class="songs">
    <div class="subsection-title">
      <h2>Songs</h2>
    </div>
    <h3>Add a Song</h3>
    <form 
      action="{% url 'add_song' musician.id %}"
      method="POST"
      class="subsection-content"
    >
      {% csrf_token %}
      {{ song_form.as_p }}
      <button type="submit" class="btn submit">Add Song</button>
    </form>
    <h3>All Songs</h3>
    {% if musician.song_set.all.count %}
      <table>
        <thead>
          <tr><th>Song</th><th>Album</th></tr>
        </thead>
        <tbody>
          {% for song in musician.song_set.all %}
            <tr>
              <td>{{song.song_name}}</td>
              <td>{{song.album}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p class="subsection-content">No songs added yet</p>
    {% endif %}
  </section>
      <section class="streams">
      <div class="subsection-title">
        <h2>Streaming Services</h2>
      </div>
      <h3>{{ musician.name }}'s Streaming Services</h3>
      <div class="subsection-content">
        {% if musician.streams.count %}
          {% for streaming in musician.streams.all %}
            <div class="streaming-container">
              <a href="{% url 'streams_detail' streaming.id %}">
              <p>{{ streaming.streaming_service }}</p>
              </a>
            </div>
          {% endfor %}
        {% else %}
          <p class="no-streams" style="color: red">{{musician.name}} doesn't have any streaming services yet!</p>
        {% endif %}
      </div>
      <h3>Available Streaming Services</h3>
      <div class="subsection-content">
        {% if streams.count %}
          {% for streaming in streams.all %}
            <div class="streaming-container">
              <a href="{% url 'streams_detail' streaming.id %}">
                <p>{{ streaming.streaming_service }}</p>
              </a>
              <form action="{% url 'assoc_streaming' musician.id streaming.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn submit">Add Streaming Service</button>
              </form>
            </div>
          {% endfor %}
        {% else %}
        <p class="all-streams">
          {{musician.name}} already has all the available streaming services!
        </p>
      {% endif %}
      </div>
    </section>
  </div>
</div>
{% endblock %}

main_app/templates/musicians/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/musician-index.css' %}"/>
{% endblock %}

{% block content %}

<section class="page-header">
  <h1>Musician List</h1>
  <img src="{% static 'images/music-cat.png' %}" alt="A music cat" />
  <img src="{% static 'images/music-bear.png' %}" alt="A music bear" />
  <img src="{% static 'images/music-croc.png' %}" alt="A music croc" />
  <img src="{% static 'images/music-owl.png' %}" alt="A music owl" />
</section>

<section class="card-container">
  {% for musician in musicians %}
    <div class="card">
      <a href="{% url 'musicians_detail' musician.id %}">
        <div class="card-content">
          <div class="card-img-container">
            <img 
              src="{% static 'images/musician-icon.svg' %}" 
              alt="A Musician"
            >
          </div>
          <h2 class="card-title">{{ musician.name }}</h2>
            <p>Is a {{ musician.age }} year old {{ musician.genre}} artist.</p>
            <p><small>{{ musician.description }}</small></p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/musician-icon.svg' %}" alt="A Musician"/>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}